### PR TITLE
Add log for the request routing to s3 object

### PR DESCRIPTION
**Pull request by dichn**

### CODE REVIEW

**Review by rohanpm — CHANGES_REQUESTED** [review]
If the CI failure is triggered by this change, it'll need to be fixed.

**Comment by rohanpm** [comment]
The CI failure is triggered by this commit and would be fixed by https://github.com/release-engineering/exodus-gw/pull/430.

**Comment by rohanpm** [comment]
Please try rebasing this now to get CI passing.

**Comment by dichn** [comment]
Re-pushed after rebasing, and passed the CI.
Put "draft" status to "ready for review".

**Review by rohanpm — APPROVED** [review]

**Pull request merged**
