### PR TITLE
Add noload option to cleanup queries [RHELDST-14737]

### PR DESCRIPTION
**Pull request by negillett**
Previously, when loading Tasks and Publishes for scheduled cleanup operations, any children were automatically loaded as well, using more memory than necessary and causing crashes by exceeding the limits set in OpenShift.

This commit adds the noload option to cleanup queries with keys="*" so that no children are ever loaded.

Because children aren't loaded, publish items are no longer deleted automatically. So a delete query was added for items when cleaning up old publishes.

### CODE REVIEW

**Comment by negillett** [comment]
Safety scanner is blocking for pre-versions of packages... Would using pre-versions not in itself be a safety risk?

**Review by rohanpm — DISMISSED** [review]

**Comment by rohanpm** [comment]
> Safety scanner is blocking for pre-versions of packages... Would using pre-versions not in itself be a safety risk?

Furthermore, sqlalchemy 1 => 2 seems like a big enough deal that there is a migration guide written for it, https://docs.sqlalchemy.org/en/20/changelog/migration_20.html, so I'm guessing we can't do it by the usual automated updates.

I think the right thing to do in a case like this is something like https://github.com/release-engineering/exodus-gw/pull/492 , acknowledge this particular vulnerability and give ourselves a few months to handle the upgrade, filed separately.

**Comment by negillett** [comment]
Rebased

**Comment by negillett** [comment]
Carrying over @rohanpm's +1 from before the rebase

**Pull request merged**
