### PR TITLE
Revert "Parallelize batch writes [RHELDST-13451]"

### PR DESCRIPTION
**Pull request by crungehottman**
This reverts commit d2939b30c6fb14c00f2e89a46824ce987419a108.

### CODE REVIEW

**Comment by negillett** [comment]
I'm not yet convinced this change is causing the observed memory issue.

**Comment by crungehottman** [comment]
> I'm not yet convinced this change is causing the observed memory issue.

I'm not fully convinced either, but I'll leave this here for a while in case we decide we need to revert it.

**Review by rohanpm — CHANGES_REQUESTED** [review]
I'd rather not revert it, instead find a way to only move forward.

I made a suggestion on RHELDST-13451 about reducing memory usage by setting some env vars.  If it doesn't work, I'd still rather we try some other things like reducing the thread count before reverting this.

**Comment by negillett** [comment]
The memory problem on OCP doesn't seem related to threading at all anyway. This change doesn't alter the historical memory usage either.

**Review by negillett — CHANGES_REQUESTED** [review]
I think we're good to close this.

**Comment by crungehottman** [comment]
> I think we're good to close this.

Thanks for the reminder :)

**Pull request closed without merging**
