### PR TITLE
Autoformat existing code with Black

### PR DESCRIPTION
**Pull request by nathanegillett**

### CODE REVIEW

**Comment by nathanegillett** [comment]
Not sure how these made it past our local tox and pre-commit checks.

**Review by lioramilbaum — CHANGES_REQUESTED** [review]
Please take a look why the CI is broken

**Comment by rohanpm** [comment]
> Not sure how these made it past our local tox and pre-commit checks.

Usually that means the output of the tool has changed in a new release, so you may need to ensure you're using exactly the version applied in CI which appears to be black==20.8b1.

**Comment by nathanegillett** [comment]
Very strange. I'm not seeing the issue locally anymore. Black _must have_ upgraded without my knowledge at some point on my system.

**Pull request closed without merging**
